version: '3.7'
services:
  angular-service:
    container_name: angulartest
    build: 
      context: .
      target: 'dev-stage'
    volumes:
      - '.:/usr/src/app'
    ports: 
      - '4200:4200'
    command: >
      bash -c "npm install && ng serve --host 0.0.0.0 --port 4200"

